class org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause extends java.lang.Exception
{

    private void <init>()
    {
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause this;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause;

        specialinvoke this.<java.lang.Exception: void <init>()>();

        return;
    }

    public void getTargetException()
    {
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause this;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause;

        return;
    }

    void <init>(org.apache.commons.lang3.exception.ExceptionUtilsTest$1)
    {
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause this;
        org.apache.commons.lang3.exception.ExceptionUtilsTest$1 x0;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause;

        x0 := @parameter0: org.apache.commons.lang3.exception.ExceptionUtilsTest$1;

        specialinvoke this.<org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithoutCause: void <init>()>();

        return;
    }
}
